clc;
clear all;
echo off


figure('Position', [80 80 800 800])


         

caution = uicontrol('Style', 'text',...
         'String', 'Symbol:',...
          'BackGroundColor',[0.8 0.8 0.8],...
         'Position', [5 170 50 30]);

mycontrol = uicontrol(gcf, 'style', 'edit',...
     'BackGroundColor',[1 1 1],...
            'position', [5 160 55 22]);
smbl = ['smbl=get(gco, ''string'');'];
set(mycontrol, 'callBack', smbl)
   
caution = uicontrol('Style', 'text',...
         'String', 'Date:',...
          'BackGroundColor',[0.8 0.8 0.8],...
         'Position', [5 115 55 30]);

caution = uicontrol('Style', 'text',...
         'String', '(example:',...
          'BackGroundColor',[0.8 0.8 0.8],...
         'Position', [5 104 55 30]);
  
caution = uicontrol('Style', 'text',...
         'String', '12-29-04)',...
          'BackGroundColor',[0.8 0.8 0.8],...
         'Position', [5 90 55 30]);
     
mycontrol = uicontrol(gcf, 'style', 'edit',...
     'BackGroundColor',[1 1 1],...
            'position', [5 80 60 22]);
date1 = ['date1=get(gco, ''string'');'];
set(mycontrol, 'callBack', date1)

go = uicontrol('Style', 'pushbutton', 'String', 'GET DATA',...
        'BackgroundColor','yellow',...
    'ForegroundColor','black',...
             'FontWeight', 'bold',...     
  'Position', [5 40 65 30],'Callback', 'sqqe');






hpop0 = uicontrol('Style', 'popup',...
       'String', 'days|20|40|80 |120 |180 |200 |220  ',...
       'Position', [5 15 50 10]);

caution = uicontrol('Style', 'text',...
         'String', ' fast<slow : ',...
         'Position', [70 7 60 15]);

hpop1 = uicontrol('Style', 'popup',...
       'String', 'fast|2|5|7 |10 |15 |20 |30 |35  ',...
       'Position', [140 15 50 10]);
    
hpop2 = uicontrol('Style', 'popup',...
       'String', 'slow|2|5|7 |10 |15 |20 |30|35  ',...
       'Position', [210 15 50 10]);
   
go = uicontrol('Style', 'pushbutton', 'String', 'RESULTS',...
        'BackgroundColor','green',...
    'ForegroundColor','black',...
             'FontWeight', 'bold',...     
  'Position', [400 4 80 20], 'Callback', 'ave');




    
    
    
