function indicatorChartWPR(w1)
%INDICATORCHARTWPR(W1)
%  W1:  vector of y data

%  Auto-generated by MATLAB on 28-Mar-2011 16:22:21

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
box(axes1,'on');
hold(axes1,'all');

% Create plot
plot(w1,'DisplayName','Williams %R');

% Create reference lines
r1 = refline(0, -20);
r2 = refline(0, -80);
set(r1, 'Color', 'r', 'DisplayName', 'Over bought')
set(r2, 'Color', 'g', 'DisplayName', 'Over sold')

% Create xlabel
xlabel('Serial time number');

% Create ylabel
ylabel('Williams %R');

% Create title
title('Williams %R');

% Create legend
legend(axes1, 'Location', 'Best')

