function indicatorChartMA(YMatrix1)
%INDICATORCHARTMA(YMATRIX1)
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 08-Mar-2011 10:45:23

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'YGrid','on','XGrid','on');
box(axes1,'on');
hold(axes1,'all');

% Create multiple lines using matrix input to plot
plot1 = plot(YMatrix1,'Parent',axes1);
set(plot1(1),'DisplayName','Close');
set(plot1(2),'DisplayName','Lead');
set(plot1(3),'DisplayName','Lag');

% Create xlabel
xlabel('Serial day number');

% Create ylabel
ylabel('Price ($)');

% Create title
title('Daily LCO data with two indicators');

% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Location','Best');

