mex -v vtkPolyDataRenderer.cpp ...
    -I'C:\Program Files\VTK 5.0\src5p0\VTK\Common' ...
    -I'C:\Program Files\VTK 5.0\src5p0\VTK\Filtering' ...
    -I'C:\Program Files\VTK 5.0\src5p0\VTK\Rendering' ...
    -I'C:\Program Files\VTK 5.0\src5p0\Build' ...
    -L'C:\Program Files\VTK 5.0\src5p0\Build\bin\debug' ...
    -lvtkCommon ...
    -lvtkFiltering ...
    -lvtkRendering 