function demo_3class
%DEMO_3CLASS    Classification problem demonstration for 3
%               classes. 
%
%      Description
%      The data used in the demonstration program is the same used
%      by Radford M. Neal in his three-way classification example
%      in Software for Flexible Bayesian Modeling
%      (http://www.cs.toronto.edu/~radford/fbm.software.html) The
%      data consists of 1000 4-D vectors which are classified into
%      three classes. The data is generated by drawing the
%      components of vector, x1, x2, x3 and x4, uniformly form
%      (0,1). The class of each vector is selected according to the
%      first two components of the vector, x_1 and x_2. After this
%      a Gaussian noise with standard deviation of 0.1 has been
%      added to every component of the vector. Because there are
%      two irrelevant components in the input vector a prior with
%      ARD should be of help. 
%
%      The data is divided into two parts, trainig set of 400 units
%      and test set of 600 units. The percentage of missclassified
%      units is found with the test set.
%
%      The demonstration program does not sample for real, because
%      it would require so much time. The main sampling state is
%      commented out from the program and instead a saved network
%      structure is loaded and used to make predictions (see lines
%      XX-XX).
%

% Copyright (c) 2005 Jarno Vanhatalo, Aki Vehtari 

% This software is distributed under the GNU General Public 
% License (version 2 or later); please refer to the file 
% License.txt, included with the software, for details.

% This demonstration is based on the dataset used in the book Pattern Recognition and
% Neural Networks by B.D. Ripley (1996) Cambridge University Press ISBN 0 521
% 46986 7

disp(' ')
disp(' The data used in the demonstration program is the same used ')
disp(' by Radford M. Neal in his three-way classification example ')
disp(' in Software for Flexible Bayesian Modeling ')
disp(' (http://www.cs.toronto.edu/~radford/fbm.software.html) The ')
disp(' data consists of 1000 4-D vectors which are classified into ')
disp(' three classes. The data is generated by drawing the ')
disp(' components of vector, x1, x2, x3 and x4, uniformly form ')
disp(' (0,1). The class of each vector is selected according to the ')
disp(' first two components of the vector, x_1 and x_2. After this ')
disp(' a Gaussian noise with standard deviation of 0.1 has been ')
disp(' added to every component of the vector. Because there are ')
disp(' two irrelevant components in the input vector a prior with ')
disp(' ARD should be of help. ')
disp(' ')
disp(' ')

% Load the data
S = which('demo_3class');
L = strrep(S,'demo_3class.m','demos/cdata');
x=load(L);
y=repmat(0,size(x,1),3);
y(x(:,5)==0,1) = 1;
y(x(:,5)==1,2) = 1;
y(x(:,5)==2,3) = 1;
x(:,end)=[];

% Divide the data into training and test parts.
xt = x(401:end,:);
x=x(1:400,:);
yt=y(401:end,:);
y=y(1:400,:);

disp(' ')
disp(' First we create an MLP network for classification model with softmax')
disp(' output function (mlp2c). Function mlp initializes weights to zero.')
disp(' A Gaussian multivariate hierarchical prior with ARD is created ')
disp(' for network. ')
disp(' ')

nin=size(x,2);
nhid=8;
nout=size(y,2);
% create MLP with logistic output function ('mlp2b')
net = mlp2('mlp2c', nin, nhid, nout);

% Create a Gaussian multivariate hierarchical prior with ARD 
net=mlp2normp(net, {{repmat(10,1,net.nin) 0.05 1 -0.05 2}...  % input-hidden weigth
                    {10 0.05 1} ...                           % bias-hidden
                    {10 -0.05 1} ...                          % hidden-output weigth
                    {10}})                                    % bias-output



% To create prior for the weights without ARD, comment out the above
% lines and remove the comment marks below.
%net=mlp2normp(net, {{10 0.05 1}...                             % input-hidden weight
%                    {10 0.05 1} ...                          % bias-hidden
%                    {10 -0.05 1} ...                         % hidden-output
%                    {1}});                                     % bias-output

disp(' ')
disp(' The starting values for sampling the weights are found with early ')
disp(' stop method. This is a quick way to get better starting point ')
disp(' for the Markov chain.') 
disp(' ')
% See Vehtari et al (2000). On MCMC sampling in Bayesian MLP neural networks.
% In Proc. IJCNN'2000.
%
% <http://www.lce.hut.fi/publications/pdf/VehtariEtAl_ijcnn2000.pdf>

% Intialize weights to zero and set the optimization parameters...
w=randn(size(mlp2pak(net)))*0.01;

fe=str2fun('mlp2c_e');
fg=str2fun('mlp2c_g');
n=length(y);
itr=1:floor(0.5*n);     % training set of data for early stop
its=floor(0.5*n)+1:n;   % test set of data for early stop
optes=scges_opt;
optes.display=1;
optes.tolfun=1e-1;
optes.tolx=1e-1;

% do scaled conjugate gradient optimization with early stopping.
[w,fs,vs]=scges(fe, w, optes, fg, net, x(itr,:),y(itr,:), net,x(its,:),y(its,:));
net=mlp2unpak(net,w);

disp(' ')
disp(' Now that the initial values for weigths are found we can set the ')
disp(' starting values for weights hyperparameters (variance of weight). ')
disp(' The variance of each weight can be aproximated from the early stop ')
disp(' values of the weight. The starting values for other hyperparameters ')
disp(' are found by sampling one sample of each parameter without ') 
disp(' persistence for weights. ')
disp(' ')

% Set the starting values for hyperparameter of the weights to be the
% variance of the early stopped weight.
shypw1 = std(net.w1,0,2)';
shypb1 = std(net.b1);
shypw2 = std(net.w2(:));

net=mlp2normp(net, {{shypw1  0.05 1 -0.05 2}...    % input-hidden weigth
                    {shypb1  0.05 1} ...           % bias-hidden
                    {shypw2 -0.05 1} ...           % hidden-output weigth
                    {1}})                          % bias-output

% First initialize random seed for Monte 
% Carlo sampling and set the sampling options to default.
hmc2('state', sum(100*clock));
opt=mlp2c_mcopt;
opt.sample_inputs=0; % do not use RJMCMC for input variables

% do the sampling without persistence.
opt.repeat=70;           
opt.hmc_opt.steps=10;    
opt.hmc_opt.stepadj=0.2; 
opt.gibbs=1;
opt.nsamples=1;
[r,net,rstate]=mlp2c_mc(opt, net, x, y);

disp(' ')
disp(' Here we would do the main sampling. The main sampling is skipped')
disp(' and an old network record structure is loaded in order to save')
disp(' time. To do the main sampling, uncomment mlp2b_mc line from ')
disp(' program and comment out the load lines.')
disp(' ')

% the starting values are found. Start the main sampling.
opt.hmc_opt.stepadj=0.5; 
opt.hmc_opt.persistence=1;
opt.hmc_opt.steps=40;    
opt.hmc_opt.decay=0.95;  
opt.repeat=50;           
opt.nsamples=250;
opt.hmc_opt.window=5;     


% Here we would do the main sampling. In order to save time we have
% saved one GP record structure in the software. The record (and though 
% the samples) are loaded and used in the demo. In order to do your own 
% sampling uncomment the line below.
%
%[r,net,rstate]=mlp2c_mc(opt, net, x, y, [], [], r, rstate);

L = strrep(S,'demo_3class.m','demos/3classrecord');
load(L);   % These lines load an old record structure.
rr = r;

disp(' ')
disp(' For the last we thin the record structure and make predictions ')
disp(' for test data. The number of misclassified vectors is told ')
disp(' in percentage. ')
disp(' ')

% Thin the sample chain.
r=thin(r,50,6);

% test how well the network works for test data. 
forw = mlp2fwds(r,xt);
for i=1:size(forw,3)
  tga(:,:,i) = softmax2(forw(:,:,i));
end
tga = mean(tga,3);
tt = tga==repmat(max(tga,[],2),1,size(tga,2));

% calculate the percentage of misclassified points
missed = (sum(sum(abs(tt-yt)))/2)/size(yt,1)

% plot the train data o=0, x=1
plot(x(y(:,1)==1,1),x(y(:,1)==1,2),'o');
hold on
plot(x(y(:,2)==1,1),x(y(:,2)==1,2),'x');
plot(x(y(:,3)==1,1),x(y(:,3)==1,2),'.');
hold off;

disp(' ')
disp(' The effect of ARD to the input to hidden unit weights ')
disp(' can be checked by studying  the posterior densities')
disp(' of weights prior a_k. The weights for an input to hidden ')
disp(' connection are sampled from w_kj ~ N(0,a_k), where w_kj ')
disp(' is a weight from k:th input to j:th hidden unit. Now we draw ')
disp(' the densities of weigths priors in the same plot, where it ')
disp(' can be seen that the distribution of a_1 and a_2 is more spread ')
disp(' than the ones of a_3 and a_4 ')
disp(' ')

[pp,xx]=kernelp(rr.inputHiddenSigmas(:,1));
plot(xx,pp/sum(pp))
hold on;
[pp,xx]=kernelp(rr.inputHiddenSigmas(:,2));
plot(xx,pp/sum(pp),'--')
[pp,xx]=kernelp(rr.inputHiddenSigmas(:,3));
plot(xx,pp/sum(pp),':')
[pp,xx]=kernelp(rr.inputHiddenSigmas(:,4));
plot(xx,pp/sum(pp),'-.')
legend('a_1', 'a_2', 'a_3', 'a_4')
axis([0 12 0 0.03])
hold off