function [g, gdata, gprior] = gp2r_g(w, gp, p, t)
%GP2R_G Evaluate gradient of error for Gaussian Process.
%
%	Description
%	G = GP2R_G(HP, GP, X, T) takes a gp hyper-parameter vector HP, 
%       data structure GP a matrix X of input vectors and a matrix T 
%       of target vectors, and evaluates the error gradient G. Each row of X
%	corresponds to one input vector and each row of T corresponds
%       to one target vector.
%
%	[G, GDATA, GPRIOR] = GP2R_G(GP, P, T) also returns separately  the
%	data and prior contributions to the gradient.
%
%	See also
%	GP2, GP2PAK, GP2UNPAK, GP2FWD, GP2R_E
%

% Copyright (c) 1998-2001 Aki Vehtari

% This software is distributed under the GNU General Public 
% License (version 2 or later); please refer to the file 
% License.txt, included with the software, for details.

gp=gp2unpak(gp,w);

% Calculate inverse of covariance and other terms
[invC,c,d]=gpexptrcovinv(gp,p);

b=invC*t;bt=b';
% instead of calulating trace(invC*D) calculate sum(invCv.*D(:))
% which is 67 times faster with n=215
invCv=invC(:);

gdata=zeros(size(w));gprior=gdata;i1=0; gpp=gp.p;
i1=i1+1;
D=2.*c;

% Evaluate the data and prior contribution gradient with respect to 
% expScale
gdata(i1)=0.5.*(sum(invCv.*D(:)) - bt*(D*b));
gprior(i1)=feval(gpp.expScale.fg, ...
                 gp.expScale, ...
                 gpp.expScale.a, 'x').*gp.expScale+2;
% Evaluate the prior contribution of gradient with respect to expSigmas
if ~isempty(gpp.expSigmas.p)
  i1=i1+1;
  gprior(i1)=...
      feval(gpp.expSigmas.p.s.fg, ...
            gpp.expSigmas.a.s,...
            gpp.expSigmas.p.s.a, 'x').*gpp.expSigmas.a.s+2 ...
      +feval(gpp.expSigmas.fg, ...
             gp.expSigmas, ...
             gpp.expSigmas.a, 's').*gpp.expSigmas.a.s;
  if any(strcmp(fieldnames(gpp.expSigmas.p),'nu'))
    i1=i1+1;
    gprior(i1)=...
        feval(gpp.expSigmas.p.nu.fg, ...
              gpp.expSigmas.a.nu,...
              gpp.expSigmas.p.nu.a, 'x').*gpp.expSigmas.a.nu+2 ...
        +feval(gpp.expSigmas.fg, ...
               gp.expSigmas, ...
               gpp.expSigmas.a, 'nu').*gpp.expSigmas.a.nu;
  end
end
% Evaluate the data contribution of gradient with respect to expSigmas
if length(gp.expSigmas)>1
  for i2=1:gp.nin
    i1=i1+1;
    D=-2.*d(:,:,i2).*c;
    gdata(i1)=0.5.*(sum(invCv.*D(:)) - bt*(D*b));
    gprior(i1)=feval(gpp.expSigmas.fg, ...
                     gp.expSigmas(i2), ...
                     gpp.expSigmas.a, 'x').*gp.expSigmas(i2)+2;
  end
else
  i1=i1+1;
  D=-2.*d.*c;
  gdata(i1)=0.5.*(sum(invCv.*D(:)) - bt*(D*b));
  gprior(i1)=feval(gpp.expSigmas.fg, ...
                   gp.expSigmas, ...
                   gpp.expSigmas.a, 'x').*gp.expSigmas+2;
end
% Evaluate the data and prior contribution of gradient with respect to 
% noiseSigmas
if ~isempty(gp.noiseSigmas) & ~isempty(gpp.noiseSigmas)
  if isempty(gp.noiseVariances)
    i1=i1+1;
    D=2*gp.noiseSigmas.^2;
    gdata(i1)=0.5.*D.*(trace(invC) - b'*b);
    gprior(i1)=feval(gpp.noiseSigmas.fg, ...
		     gp.noiseSigmas, ...
		     gpp.noiseSigmas.a, 'x').*gp.noiseSigmas+2;
  else
    if ~isempty(gpp.noiseSigmas.p)
      if ~isempty(gpp.noiseSigmas.p.s.p)
	i1=i1+1;
	gprior(i1)=...
	    feval(gpp.noiseSigmas.p.s.p.s.fg, ...
		  gpp.noiseSigmas.p.s.a.s, ...
		  gpp.noiseSigmas.p.s.p.s.a,'x').*gpp.noiseSigmas.p.s.a.s+2 ...
	    +feval(gpp.noiseSigmas.p.s.fg, ...
		   gpp.noiseSigmas.a.s, ...
		   gpp.noiseSigmas.p.s.a, 's').*gpp.noiseSigmas.p.s.a.s;
      end
      i2=i1+length(gpp.noiseSigmas.a.s);
      i1=i1+1;
      gprior(i1:i2)=...
	  feval(gpp.noiseSigmas.p.s.fg, ...
		gpp.noiseSigmas.a.s, ...
		gpp.noiseSigmas.p.s.a, 'x').*gpp.noiseSigmas.a.s+2 ...
	  +feval(gpp.noiseSigmas.fg, ...
		 gp.noiseSigmas, ...
		 gpp.noiseSigmas.a, 's').*gpp.noiseSigmas.a.s;
      i1=i2;
      if any(strcmp(fieldnames(gpp.noiseSigmas.p),'nu'))
	if ~isempty(gpp.noiseSigmas.p.nu.p)
	  i1=i1+1;
	  gprior(i1)=...
	      feval(gpp.noiseSigmas.p.nu.p.s.fg, ...
		    gpp.noiseSigmas.p.nu.a.s, ...
		    gpp.noiseSigmas.p.nu.p.s.a,'x').*gpp.noiseSigmas.p.nu.a.s+2 ...
	      +feval(gpp.noiseSigmas.p.nu.fg, ...
		     gpp.noiseSigmas.a.nu, ...
		     gpp.noiseSigmas.p.nu.a, 's').*gpp.noiseSigmas.p.nu.a.s;
	end
	i2=i1+length(gpp.noiseSigmas.a.nu);
	i1=i1+1;
	gprior(i1:i2)=...
	    feval(gpp.noiseSigmas.p.nu.fg, ...
		  gpp.noiseSigmas.a.nu, ...
		  gpp.noiseSigmas.p.nu.a, 'x').*gpp.noiseSigmas.a.nu+2 ...
	    +feval(gpp.noiseSigmas.fg, ...
		   gp.noiseSigmas, ...
		   gpp.noiseSigmas.a, 'nu').*gpp.noiseSigmas.a.nu;
      end
    end
  end
end

g = gdata + gprior;
