function [e, edata, eprior] = gp2r_e(w, gp, p, t)
%GP2R_E	Evaluate error function for Gaussian Process.
%
%	Description
%	E = GP2R_E(GP, P, T) takes a gp data structure GP together
%	with a matrix P of input vectors and a matrix T of target vectors,
%	and evaluates the error function E. The choice of error function
%	corresponds to the output unit activation function. Each row of P
%	corresponds to one input vector and each row of T corresponds to one
%	target vector.
%
%	[E, EDATA, EPRIOR] = GP2R_E(GP, P, T) also returns the data and
%	prior components of the total error.
%
%	See also
%	GP2, GP2PAK, GP2UNPAK, GP2FWD, GP2R_G
%

% Copyright (c) 1998-2001 Aki Vehtari

% This software is distributed under the GNU General Public 
% License (version 2 or later); please refer to the file 
% License.txt, included with the software, for details.

gp=gp2unpak(gp, w);

% Evaluate the data contribution to the error.
n=length(p);
edata=gpexpedata(gp,p,t);

% Evaluate the prior contribution to the error.
eprior=0; gpp=gp.p;
eprior=eprior...
       +feval(gpp.expScale.fe, ...
              gp.expScale, gpp.expScale.a)...
       +2.*log(gp.expScale);
if ~isempty(gpp.expSigmas.p)
  eprior=eprior...
         +feval(gpp.expSigmas.p.s.fe, ...
                gpp.expSigmas.a.s, gpp.expSigmas.p.s.a)...
         +2.*log(gpp.expSigmas.a.s);
  if any(strcmp(fieldnames(gpp.expSigmas.p),'nu'))
    eprior=eprior...
           +feval(gpp.expSigmas.p.nu.fe, ...
                  gpp.expSigmas.a.nu, gpp.expSigmas.p.nu.a)...
           +2.*log(gpp.expSigmas.a.nu);
  end
end
eprior=eprior...
       +feval(gpp.expSigmas.fe, ...
              gp.expSigmas, gpp.expSigmas.a)...
       +sum(2.*log(gp.expSigmas));

if ~isempty(gp.noiseSigmas) & ~isempty(gpp.noiseSigmas)
  if ~isempty(gpp.noiseSigmas.p)
    if ~isempty(gpp.noiseSigmas.p.s.p)
      eprior=eprior...
	     +feval(gpp.noiseSigmas.p.s.p.s.fe, ...
		    gpp.noiseSigmas.p.s.a.s, gpp.noiseSigmas.p.s.p.s.a)...
	     +2.*log(gpp.noiseSigmas.p.s.a.s);
    end
    eprior=eprior...
	   +feval(gpp.noiseSigmas.p.s.fe, ...
		  gpp.noiseSigmas.a.s, gpp.noiseSigmas.p.s.a)...
	   +sum(2.*log(gpp.noiseSigmas.a.s));
    if any(strcmp(fieldnames(gpp.noiseSigmas.p),'nu'))
      if ~isempty(gpp.noiseSigmas.p.nu.p)
	eprior=eprior...
	       +feval(gpp.noiseSigmas.p.nu.p.s.fe, ...
		      gpp.noiseSigmas.p.nu.a.s, gpp.noiseSigmas.p.nu.p.s.a)...
	       +2.*log(gpp.noiseSigmas.p.nu.a.s);
      end
      eprior=eprior...
	     +feval(gpp.noiseSigmas.p.nu.fe, ...
		    gpp.noiseSigmas.a.nu, gpp.noiseSigmas.p.nu.a)...
	     +sum(2.*log(gpp.noiseSigmas.a.nu));
    end
  end
  eprior=eprior...
	 +feval(gpp.noiseSigmas.fe, ...
		gp.noiseSigmas, gpp.noiseSigmas.a)...
	 +sum(2.*log(gp.noiseSigmas));
end

e = edata + eprior;
