/*
 * ImagePanel.java
 *
 * Created on 14 August 2006, 09:21
 */

package com.mathworks.demos.finance.portoptdemo;
import java.awt.Color;
import java.awt.Image;
import java.awt.Font;
import java.util.ResourceBundle;
/**
 *
 * @author  elwinc
 */
public class ImagePanel extends javax.swing.JPanel implements CustomJComponent {
    
    /** Creates new form ImagePanel */
    public ImagePanel() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        fImageLabel = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        setOpaque(false);
        fImageLabel.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(fImageLabel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(jScrollPane1, gridBagConstraints);

    }// </editor-fold>//GEN-END:initComponents

    public void setImage(Image im)
    {
        fImageLabel.setBackground(Color.WHITE);
        fImageLabel.setOpaque(true);
        fImageLabel.setIcon(new javax.swing.ImageIcon(im));
    }
    
    public void clearImage()
    {
        fImageLabel.setIcon(null);
    }

    public void setFontSize(int size)
    {
        fImageLabel.setFont(new Font("Dialog", Font.PLAIN, size));
    }
    
    public void updateForLocale(ResourceBundle localSettings)
    {
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fImageLabel;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    
}
