/*
 * InputDataPanel.java
 *
 * Created on 09 August 2006, 12:55
 */

package com.mathworks.demos.finance.portoptdemo;
import java.awt.Font;
import java.awt.FontMetrics;
import java.util.ResourceBundle;

/**
 *
 * @author  elwinc
 */
public class InputDataPanel extends javax.swing.JPanel implements CustomJComponent {
    
    /** Creates new form InputDataPanel */
    public InputDataPanel() {
        fInputsTableModel = new InputsTableModel();
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;
        javax.swing.JScrollPane jScrollPane2;

        jScrollPane2 = new javax.swing.JScrollPane();
        fInputsTable = new javax.swing.JTable(fInputsTableModel);

        setLayout(new java.awt.GridBagLayout());

        setDoubleBuffered(false);
        fInputsTable.setRowSelectionAllowed(false);
        jScrollPane2.setViewportView(fInputsTable);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(jScrollPane2, gridBagConstraints);

    }// </editor-fold>//GEN-END:initComponents
    
    
    public void setDataStats(String[] names, double[] mean, double[] std)
    {
        fInputsTableModel.setData(names, mean, std);
   }
    
    public void clearData()
    {
        fInputsTableModel.clearData();
    }
    
    public void setFontSize(int size)
    {
        Font font = new Font("Dialog", Font.PLAIN, size);
        FontMetrics fm = getFontMetrics(font);
        fInputsTable.setFont(font);
        fInputsTable.setRowHeight(fm.getHeight());
        fInputsTable.getTableHeader().setFont(font);
    }
    
    public void updateForLocale(ResourceBundle localSettings)
    {
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable fInputsTable;
    // End of variables declaration//GEN-END:variables

    private InputsTableModel fInputsTableModel;
}
