/*
 * mainDesktopFrame.java
 *
 * Created on 10 August 2006, 09:23
 */

package com.mathworks.demos.finance.portoptdemo;
import javax.swing.*;
import java.io.File;
import java.awt.Image;
import java.awt.Cursor;
import java.awt.Font;
import java.awt.FontMetrics;
import java.util.Locale;
import java.util.ResourceBundle;

/**
 *
 * @author  elwinc
 */
public class mainDesktopFrame extends javax.swing.JFrame implements CustomJComponent {
    
    /** Creates new form mainDesktopFrame */
    public mainDesktopFrame() {

        fPortOptWrapper = new PortOptWrapper();
        fCovMatTableModel = new CovMatTableModel();

        initComponents();

        fParamsPanel.setOptimiseButtonListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optimiseButtonActionPerformed(evt);
            }
        });

        //set the titles according to the locale
        Locale currentLocale = Locale.getDefault();
        ResourceBundle localSettings = ResourceBundle.getBundle("PortOptDemo", currentLocale);
        updateForLocale(localSettings);

        //use the current layout as the default layout
        fScrollableDesktop.generateDefaultFromCurrentLayout();
        
        //set the font size to the default
        setFontSize(fFontSize);
        
        // Enable/Disable the windows
        enableContents(fInputDataPanel, true);
        enableContents(fPricesPlotPanel, true);
        
        enableContents(fParamsPanel, false);

        enableContents(fOutputsPanel, false);
        enableContents(fEFrontPanel, false);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        fFileChooser = new javax.swing.JFileChooser();
        fFontSizeDialog = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        fFontSizeSpinner = new javax.swing.JSpinner();
        fFontSizeOKButton = new javax.swing.JButton();
        fFontSizeCancelButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        fScrollableDesktop = new com.mathworks.demos.finance.portoptdemo.MDIDesktopPane();
        fInputDataFrame = new javax.swing.JInternalFrame();
        fInputDataPanel = new com.mathworks.demos.finance.portoptdemo.InputDataPanel();
        fCovMatFrame = new javax.swing.JInternalFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        fCovMatTable = new javax.swing.JTable(fCovMatTableModel);
        fParamsFrame = new javax.swing.JInternalFrame();
        fParamsPanel = new com.mathworks.demos.finance.portoptdemo.ParamsPanel();
        fOutputsFrame = new javax.swing.JInternalFrame();
        fOutputsPanel = new com.mathworks.demos.finance.portoptdemo.PortOptResultsPanel();
        fEFrontPlotFrame = new javax.swing.JInternalFrame();
        fEFrontPanel = new com.mathworks.demos.finance.portoptdemo.ImagePanel();
        fPricePlotFrame = new javax.swing.JInternalFrame();
        fPricesPlotPanel = new com.mathworks.demos.finance.portoptdemo.ImagePanel();
        fMenuBar1 = new javax.swing.JMenuBar();
        fFileMenu = new javax.swing.JMenu();
        fImportMenuItem = new javax.swing.JMenuItem();
        fChangeFontMenuItem = new javax.swing.JMenuItem();
        fRunMenu = new javax.swing.JMenu();
        fRunPortOptMenuItem = new javax.swing.JMenuItem();
        fViewMenu = new javax.swing.JMenu();
        fInputDataViewMenuItem = new javax.swing.JCheckBoxMenuItem();
        fCovMatViewMenuItem = new javax.swing.JCheckBoxMenuItem();
        fPricesPlotViewMenuItem = new javax.swing.JCheckBoxMenuItem();
        fParamViewMenuItem = new javax.swing.JCheckBoxMenuItem();
        fOutputViewMenuItem = new javax.swing.JCheckBoxMenuItem();
        fEFrontViewMenuItem = new javax.swing.JCheckBoxMenuItem();
        fWindowMenu = new WindowMenu(fScrollableDesktop);

        fFontSizeDialog.getContentPane().setLayout(new java.awt.GridBagLayout());

        fFontSizeDialog.setTitle("Change Font Size");
        fFontSizeDialog.setModal(true);
        fFontSizeDialog.setResizable(false);
        fFontSizeDialog.setBounds(100, 100, 200, 150);
        jLabel1.setText("Font Size");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        fFontSizeDialog.getContentPane().add(jLabel1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        fFontSizeDialog.getContentPane().add(fFontSizeSpinner, gridBagConstraints);

        fFontSizeOKButton.setText("OK");
        fFontSizeOKButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fFontSizeOKButtonActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 5, 5);
        fFontSizeDialog.getContentPane().add(fFontSizeOKButton, gridBagConstraints);

        fFontSizeCancelButton.setText("Cancel");
        fFontSizeCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fFontSizeCancelButtonActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 5, 5);
        fFontSizeDialog.getContentPane().add(fFontSizeCancelButton, gridBagConstraints);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Portfolio Optimisation Tool");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        fScrollableDesktop.setPreferredSize(new java.awt.Dimension(800, 800));
        fInputDataFrame.getContentPane().setLayout(new java.awt.GridBagLayout());

        fInputDataFrame.setClosable(true);
        fInputDataFrame.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        fInputDataFrame.setForeground(java.awt.Color.white);
        fInputDataFrame.setIconifiable(true);
        fInputDataFrame.setMaximizable(true);
        fInputDataFrame.setResizable(true);
        fInputDataFrame.setPreferredSize(new java.awt.Dimension(300, 200));
        try {
            fInputDataFrame.setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        fInputDataFrame.setVisible(true);
        fInputDataFrame.addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                fInputDataFrameInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        fInputDataFrame.getContentPane().add(fInputDataPanel, gridBagConstraints);

        fInputDataFrame.setBounds(0, 0, 300, 200);
        fScrollableDesktop.add(fInputDataFrame, javax.swing.JLayeredPane.DEFAULT_LAYER);

        fCovMatFrame.getContentPane().setLayout(new java.awt.GridBagLayout());

        fCovMatFrame.setClosable(true);
        fCovMatFrame.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        fCovMatFrame.setIconifiable(true);
        fCovMatFrame.setMaximizable(true);
        fCovMatFrame.setResizable(true);
        fCovMatFrame.setVisible(true);
        fCovMatFrame.addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                fCovMatFrameInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        fCovMatTable.setModel(fCovMatTable.getModel());
        jScrollPane1.setViewportView(fCovMatTable);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        fCovMatFrame.getContentPane().add(jScrollPane1, gridBagConstraints);

        fCovMatFrame.setBounds(0, 200, 300, 200);
        fScrollableDesktop.add(fCovMatFrame, javax.swing.JLayeredPane.DEFAULT_LAYER);

        fParamsFrame.getContentPane().setLayout(new java.awt.GridBagLayout());

        fParamsFrame.setClosable(true);
        fParamsFrame.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        fParamsFrame.setIconifiable(true);
        fParamsFrame.setMaximizable(true);
        fParamsFrame.setResizable(true);
        fParamsFrame.setVisible(true);
        fParamsFrame.addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                fParamsFrameInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        fParamsFrame.getContentPane().add(fParamsPanel, gridBagConstraints);

        fParamsFrame.setBounds(0, 400, 300, 200);
        fScrollableDesktop.add(fParamsFrame, javax.swing.JLayeredPane.DEFAULT_LAYER);

        fOutputsFrame.getContentPane().setLayout(new java.awt.GridBagLayout());

        fOutputsFrame.setClosable(true);
        fOutputsFrame.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        fOutputsFrame.setIconifiable(true);
        fOutputsFrame.setMaximizable(true);
        fOutputsFrame.setResizable(true);
        fOutputsFrame.setVisible(true);
        fOutputsFrame.addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                fOutputsFrameInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        fOutputsFrame.getContentPane().add(fOutputsPanel, gridBagConstraints);

        fOutputsFrame.setBounds(0, 600, 300, 200);
        fScrollableDesktop.add(fOutputsFrame, javax.swing.JLayeredPane.DEFAULT_LAYER);

        fEFrontPlotFrame.getContentPane().setLayout(new java.awt.GridBagLayout());

        fEFrontPlotFrame.setClosable(true);
        fEFrontPlotFrame.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        fEFrontPlotFrame.setIconifiable(true);
        fEFrontPlotFrame.setMaximizable(true);
        fEFrontPlotFrame.setResizable(true);
        fEFrontPlotFrame.setVisible(true);
        fEFrontPlotFrame.addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                fEFrontPlotFrameInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        fEFrontPlotFrame.getContentPane().add(fEFrontPanel, gridBagConstraints);

        fEFrontPlotFrame.setBounds(300, 400, 500, 400);
        fScrollableDesktop.add(fEFrontPlotFrame, javax.swing.JLayeredPane.DEFAULT_LAYER);

        fPricePlotFrame.getContentPane().setLayout(new java.awt.GridBagLayout());

        fPricePlotFrame.setClosable(true);
        fPricePlotFrame.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        fPricePlotFrame.setIconifiable(true);
        fPricePlotFrame.setMaximizable(true);
        fPricePlotFrame.setResizable(true);
        fPricePlotFrame.setVisible(true);
        fPricePlotFrame.addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                fPricePlotFrameInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        fPricePlotFrame.getContentPane().add(fPricesPlotPanel, gridBagConstraints);

        fPricePlotFrame.setBounds(300, 0, 500, 400);
        fScrollableDesktop.add(fPricePlotFrame, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane2.setViewportView(fScrollableDesktop);

        getContentPane().add(jScrollPane2, java.awt.BorderLayout.CENTER);
        
    	try
    	{
	    	//Open the file chooser in the "current" directory the first time around.
	    	//Start by creating a file in the current directory
	        File f = new File(new File(".").getCanonicalPath());
	        // Set the current directory
	        fFileChooser.setCurrentDirectory(f);
    	}
    	catch(Exception ex)
    	{
    	}

    	// Do not allow multi-select on files
        if(fFileChooser.isMultiSelectionEnabled())
            fFileChooser.setMultiSelectionEnabled(false);
        
        fFileMenu.setText("File");
        fImportMenuItem.setText("Import Data...");
        fImportMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fImportMenuItemActionPerformed(evt);
            }
        });

        fFileMenu.add(fImportMenuItem);

        fChangeFontMenuItem.setText("Change Font Size...");
        fChangeFontMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fChangeFontMenuItemActionPerformed(evt);
            }
        });

        fFileMenu.add(fChangeFontMenuItem);

        fMenuBar1.add(fFileMenu);

        fRunMenu.setText("Run");
        fRunPortOptMenuItem.setText("Portfolio Optimisation");
        fRunPortOptMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fRunPortOptMenuItemActionPerformed(evt);
            }
        });

        fRunMenu.add(fRunPortOptMenuItem);

        fMenuBar1.add(fRunMenu);

        fViewMenu.setText("View");
        fInputDataViewMenuItem.setSelected(true);
        fInputDataViewMenuItem.setText("Data Statistics");
        fInputDataViewMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fInputDataViewMenuItemActionPerformed(evt);
            }
        });

        fViewMenu.add(fInputDataViewMenuItem);

        fCovMatViewMenuItem.setSelected(true);
        fCovMatViewMenuItem.setText("Covariance Matrix");
        fCovMatViewMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fCovMatViewMenuItemActionPerformed(evt);
            }
        });

        fViewMenu.add(fCovMatViewMenuItem);

        fPricesPlotViewMenuItem.setSelected(true);
        fPricesPlotViewMenuItem.setText("Prices Plot");
        fPricesPlotViewMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fPricesPlotViewMenuItemActionPerformed(evt);
            }
        });

        fViewMenu.add(fPricesPlotViewMenuItem);

        fParamViewMenuItem.setSelected(true);
        fParamViewMenuItem.setText("Optimisation Parameters");
        fParamViewMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fParamViewMenuItemActionPerformed(evt);
            }
        });

        fViewMenu.add(fParamViewMenuItem);

        fOutputViewMenuItem.setSelected(true);
        fOutputViewMenuItem.setText("Optimisation Results");
        fOutputViewMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fOutputViewMenuItemActionPerformed(evt);
            }
        });

        fViewMenu.add(fOutputViewMenuItem);

        fEFrontViewMenuItem.setSelected(true);
        fEFrontViewMenuItem.setText("Efficient Frontier");
        fEFrontViewMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fEFrontViewMenuItemActionPerformed(evt);
            }
        });

        fViewMenu.add(fEFrontViewMenuItem);

        fMenuBar1.add(fViewMenu);

        fWindowMenu.setText("Window");
        fMenuBar1.add(fWindowMenu);

        setJMenuBar(fMenuBar1);
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fEFrontPlotFrameInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_fEFrontPlotFrameInternalFrameClosing
        //use the menu item so that we get the correct behaviour in the menu
        fEFrontViewMenuItem.doClick();
    }//GEN-LAST:event_fEFrontPlotFrameInternalFrameClosing

    private void fPricePlotFrameInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_fPricePlotFrameInternalFrameClosing
        //use the menu item so that we get the correct behaviour in the menu
        fPricesPlotViewMenuItem.doClick();
    }//GEN-LAST:event_fPricePlotFrameInternalFrameClosing

    private void fOutputsFrameInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_fOutputsFrameInternalFrameClosing
        //use the menu item so that we get the correct behaviour in the menu
        fOutputViewMenuItem.doClick();
    }//GEN-LAST:event_fOutputsFrameInternalFrameClosing

    private void fParamsFrameInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_fParamsFrameInternalFrameClosing
        //use the menu item so that we get the correct behaviour in the menu
        fParamViewMenuItem.doClick();
    }//GEN-LAST:event_fParamsFrameInternalFrameClosing

    private void fCovMatFrameInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_fCovMatFrameInternalFrameClosing
        //use the menu item so that we get the correct behaviour in the menu
        fCovMatViewMenuItem.doClick();
    }//GEN-LAST:event_fCovMatFrameInternalFrameClosing

    private void fInputDataFrameInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_fInputDataFrameInternalFrameClosing
        //use the menu item so that we get the correct behaviour in the menu
        fInputDataViewMenuItem.doClick();;
    }//GEN-LAST:event_fInputDataFrameInternalFrameClosing

    
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // 2007-09-18 EYMC: dispose of the PortOptWrapper before making the frame invisible.  
    	// In R2007b, making the frame invisible first causes the call to fPortOptWrapper.dispose()
    	// to hang
    	if(fPortOptWrapper != null)
    	{
    		fPortOptWrapper.dispose();
    		fPortOptWrapper = null;
    	}

        //hide the frame
        setVisible(false);
        //then dispose
        dispose();
        
    }//GEN-LAST:event_formWindowClosing

    private void fFontSizeCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fFontSizeCancelButtonActionPerformed
        fFontSizeDialog.setVisible(false);
    }//GEN-LAST:event_fFontSizeCancelButtonActionPerformed

    private void fFontSizeOKButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fFontSizeOKButtonActionPerformed
        
        fFontSize = ((Integer)fFontSizeSpinner.getValue()).intValue();
        setFontSize(fFontSize);
        fFontSizeDialog.setVisible(false);
    }//GEN-LAST:event_fFontSizeOKButtonActionPerformed

    private void fChangeFontMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fChangeFontMenuItemActionPerformed
        fFontSizeSpinner.setValue(fFontSize);
        fFontSizeDialog.setVisible(true);
    }//GEN-LAST:event_fChangeFontMenuItemActionPerformed

    private void fCovMatViewMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fCovMatViewMenuItemActionPerformed
        fCovMatFrame.setVisible(fCovMatViewMenuItem.getState());
    }//GEN-LAST:event_fCovMatViewMenuItemActionPerformed

    private void fOutputViewMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fOutputViewMenuItemActionPerformed
        fOutputsFrame.setVisible(fOutputViewMenuItem.getState());
    }//GEN-LAST:event_fOutputViewMenuItemActionPerformed

    private void fPricesPlotViewMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fPricesPlotViewMenuItemActionPerformed
        fPricePlotFrame.setVisible(fPricesPlotViewMenuItem.getState());
    }//GEN-LAST:event_fPricesPlotViewMenuItemActionPerformed

    private void fEFrontViewMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fEFrontViewMenuItemActionPerformed
        fEFrontPlotFrame.setVisible(fEFrontViewMenuItem.getState());
    }//GEN-LAST:event_fEFrontViewMenuItemActionPerformed

    private void fRunPortOptMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fRunPortOptMenuItemActionPerformed
        doOptimisation();
    }//GEN-LAST:event_fRunPortOptMenuItemActionPerformed

    private void fParamViewMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fParamViewMenuItemActionPerformed
        fParamsFrame.setVisible(fParamViewMenuItem.getState());
    }//GEN-LAST:event_fParamViewMenuItemActionPerformed

    private void fInputDataViewMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fInputDataViewMenuItemActionPerformed
        fInputDataFrame.setVisible(fInputDataViewMenuItem.getState());
    }//GEN-LAST:event_fInputDataViewMenuItemActionPerformed

    private void fImportMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fImportMenuItemActionPerformed
        doImportData();
    }//GEN-LAST:event_fImportMenuItemActionPerformed

    
    private void optimiseButtonActionPerformed(java.awt.event.ActionEvent evt)
    {
        doOptimisation();
    }
    
    private void doImportData()
    {
        //use the PortOptFileFilter
        fFileChooser.setFileFilter(new PortOptFileFilter());

        //show the file open dialog
        int retval = fFileChooser.showOpenDialog(this);

        if(retval == JFileChooser.APPROVE_OPTION)
        {
            File file = fFileChooser.getSelectedFile();
            try
            {
                //clear all the existing data
                clearAllData();
                setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
                fPortOptWrapper.importFile(file.getAbsolutePath());

                populateInputPanels();
                //now enable the Input and Parameters panels
                enableContents(fInputDataPanel, true);
                enableContents(fPricesPlotPanel, true);
                enableContents(fParamsPanel, true);
                
                //and make them visible
                if(!fInputDataFrame.isVisible())
                    fInputDataViewMenuItem.doClick();
                if(!fPricePlotFrame.isVisible())
                    fPricesPlotViewMenuItem.doClick();
                if(!fCovMatFrame.isVisible())
                    fCovMatViewMenuItem.doClick();
                if(!fParamsFrame.isVisible())
                    fParamViewMenuItem.doClick();
                
            }
            catch(Exception e)
            {
                System.out.println("Exception: " + e.toString());
            }
            finally
            {
                 setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
            }
        }        
    }
    
    private void doOptimisation()
    {
        try
        {
            setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            //check the parameters
            if(fParamsPanel.validateParameters())
            {
                //do the optimisation
                fPortOptWrapper.optimisePortfolio(fParamsPanel.getExpectedReturns(), fParamsPanel.getMinAssetWeights(), fParamsPanel.getMaxAssetWeights());
                populateOutputPanels();

                //now enable the output panel
                enableContents(fOutputsPanel, true);
                enableContents(fEFrontPanel, true);

                //and make them visible
                if(!fOutputsFrame.isVisible())
                    fOutputViewMenuItem.doClick();
                if(!fEFrontPlotFrame.isVisible())
                    fEFrontViewMenuItem.doClick();
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Invalid stock weight limits", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        catch(Exception e)
        {
            System.out.println("Exception: " + e.toString());
        }
        finally
        {
             setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
        }
    }
    
    private void populateInputPanels()
    {
        //Table in the Inputs tab
        fInputDataPanel.setDataStats(fPortOptWrapper.getStockNames(), fPortOptWrapper.getMeanReturns(), fPortOptWrapper.getStdReturns());
        
        fCovMatTableModel.setData(fPortOptWrapper.getStockNames(),fPortOptWrapper.getCovarianceMat());
        
        //Image in the Inputs tab
        Image im = fPortOptWrapper.getPricesImage();
        fPricesPlotPanel.setImage(im);

        //Table in the Parameters tab
        fParamsPanel.setData(fPortOptWrapper.getStockNames(), fPortOptWrapper.getMeanReturns());
    }
    
    private void populateOutputPanels()
    {
        fOutputsPanel.setData(fPortOptWrapper.getPortRisks(), fPortOptWrapper.getPortReturns(), fPortOptWrapper.getStockNames(), fPortOptWrapper.getPortWeights());
        
        Image im = fPortOptWrapper.getEfficientFrontierImage();
        fEFrontPanel.setImage(im);
    }
    
    private void clearAllData()
    {
        fInputDataPanel.clearData();
        fCovMatTableModel.clearData();
        fPricesPlotPanel.clearImage();
        fParamsPanel.clearData();
        fOutputsPanel.clearData();
        fEFrontPanel.clearImage();
        
    }

    private void enableContents(javax.swing.JComponent comp, boolean value)
    {
        java.awt.Component[] all = comp.getComponents();
        for(int i=0; i < all.length; ++i)
        {
            all[i].setEnabled(value);
        }
    }
    
    public void dispose()
    {
        //dispose of the PortOptWrapper
    	if(fPortOptWrapper != null)
    	{
    		fPortOptWrapper.dispose();
    		fPortOptWrapper = null;
    	}
        //dispose of the internal frames
    	if(fCovMatFrame != null)
    	{
    		fCovMatFrame.dispose();
    		fCovMatFrame = null;
    	}
    	if(fEFrontPlotFrame != null)
    	{
    		fEFrontPlotFrame.dispose();
    		fEFrontPlotFrame = null;
    	}
    	if(fInputDataFrame != null)
    	{
    		fInputDataFrame.dispose();
    		fInputDataFrame = null;
    	}
    	if(fOutputsFrame != null)
    	{
    		fOutputsFrame.dispose();
    		fOutputsFrame = null;
    	}
    	if(fParamsFrame != null)
    	{
    		fParamsFrame.dispose();
    		fParamsFrame = null;
    	}
        if(fPricePlotFrame != null)
    	{
        	fPricePlotFrame.dispose();
        	fPricePlotFrame= null;
    	}
        //call dispose for the base class
        super.dispose();
    }

    public void setFontSize(int size)
    {
        fEFrontPanel.setFontSize(size);
        fInputDataPanel.setFontSize(size);
        fOutputsPanel.setFontSize(size);
        fParamsPanel.setFontSize(size);
        fPricesPlotPanel.setFontSize(size);
        
        Font font = new Font("Dialog", Font.PLAIN, size);
        FontMetrics fm = getFontMetrics(font);

        fCovMatTable.setFont(font);
        fCovMatTable.setRowHeight(fm.getHeight());
        fCovMatTable.getTableHeader().setFont(font);
    }
    
    // Change window and menu titles according to the local settings
    public void updateForLocale(ResourceBundle localSettings)
    {
        //The window titles
        setTitle(localSettings.getString("ApplicationTitle"));
        fInputDataFrame.setTitle(localSettings.getString("InputDataFrameTitle"));
        fCovMatFrame.setTitle(localSettings.getString("CovMatFrameTitle"));
        fPricePlotFrame.setTitle(localSettings.getString("PricesFrameTitle"));
        fParamsFrame.setTitle(localSettings.getString("ParamsFrameTitle"));
        fEFrontPlotFrame.setTitle(localSettings.getString("EfficientFrontierFrameTitle"));
        fOutputsFrame.setTitle(localSettings.getString("PortOptResultsFrameTitle"));

        //menu items
        fFileMenu.setText(localSettings.getString("FileMenuText"));
        fImportMenuItem.setText(localSettings.getString("FileImportMenuText"));
        fChangeFontMenuItem.setText(localSettings.getString("FileFontMenuText"));
        fRunMenu.setText(localSettings.getString("RunMenuText"));
        fRunPortOptMenuItem.setText(localSettings.getString("RunPortOptMenuText"));
        fViewMenu.setText(localSettings.getString("ViewMenuText"));
        fInputDataViewMenuItem.setText(localSettings.getString("InputDataFrameTitle"));
        fCovMatViewMenuItem.setText(localSettings.getString("CovMatFrameTitle"));
        fPricesPlotViewMenuItem.setText(localSettings.getString("PricesFrameTitle"));
        fParamViewMenuItem.setText(localSettings.getString("ParamsFrameTitle"));
        fOutputViewMenuItem.setText(localSettings.getString("PortOptResultsFrameTitle"));
        fEFrontViewMenuItem.setText(localSettings.getString("EfficientFrontierFrameTitle"));

        //individual frames
        fInputDataPanel.updateForLocale(localSettings);
        fPricesPlotPanel.updateForLocale(localSettings);
        fParamsPanel.updateForLocale(localSettings);
        fOutputsPanel.updateForLocale(localSettings);
        fEFrontPanel.updateForLocale(localSettings);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainDesktopFrame().setVisible(true);
            }
        });
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem fChangeFontMenuItem;
    private javax.swing.JInternalFrame fCovMatFrame;
    private javax.swing.JTable fCovMatTable;
    private javax.swing.JCheckBoxMenuItem fCovMatViewMenuItem;
    private com.mathworks.demos.finance.portoptdemo.ImagePanel fEFrontPanel;
    private javax.swing.JInternalFrame fEFrontPlotFrame;
    private javax.swing.JCheckBoxMenuItem fEFrontViewMenuItem;
    private javax.swing.JFileChooser fFileChooser;
    private javax.swing.JMenu fFileMenu;
    private javax.swing.JButton fFontSizeCancelButton;
    private javax.swing.JDialog fFontSizeDialog;
    private javax.swing.JButton fFontSizeOKButton;
    private javax.swing.JSpinner fFontSizeSpinner;
    private javax.swing.JMenuItem fImportMenuItem;
    private javax.swing.JInternalFrame fInputDataFrame;
    private com.mathworks.demos.finance.portoptdemo.InputDataPanel fInputDataPanel;
    private javax.swing.JCheckBoxMenuItem fInputDataViewMenuItem;
    private javax.swing.JMenuBar fMenuBar1;
    private javax.swing.JCheckBoxMenuItem fOutputViewMenuItem;
    private javax.swing.JInternalFrame fOutputsFrame;
    private com.mathworks.demos.finance.portoptdemo.PortOptResultsPanel fOutputsPanel;
    private javax.swing.JCheckBoxMenuItem fParamViewMenuItem;
    private javax.swing.JInternalFrame fParamsFrame;
    private com.mathworks.demos.finance.portoptdemo.ParamsPanel fParamsPanel;
    private javax.swing.JInternalFrame fPricePlotFrame;
    private com.mathworks.demos.finance.portoptdemo.ImagePanel fPricesPlotPanel;
    private javax.swing.JCheckBoxMenuItem fPricesPlotViewMenuItem;
    private javax.swing.JMenu fRunMenu;
    private javax.swing.JMenuItem fRunPortOptMenuItem;
    private com.mathworks.demos.finance.portoptdemo.MDIDesktopPane fScrollableDesktop;
    private javax.swing.JMenu fViewMenu;
    private javax.swing.JMenu fWindowMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
 

    private PortOptWrapper  fPortOptWrapper;
    private CovMatTableModel fCovMatTableModel;
    
    private int fFontSize = 12;
    
    
}
