/*
 * ParamsPanel.java
 *
 * Created on 10 August 2006, 09:45
 */

package com.mathworks.demos.finance.portoptdemo;
import java.awt.event.ActionListener;
import java.awt.Font;
import java.awt.FontMetrics;
import java.util.ResourceBundle;

/**
 *
 * @author  elwinc
 */
public class ParamsPanel extends javax.swing.JPanel  implements CustomJComponent {
    
    /** Creates new form ParamsPanel */
    public ParamsPanel() {
        fParamsTableModel = new ParamsTableModel();
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;
        javax.swing.JScrollPane jScrollPane5;

        jScrollPane5 = new javax.swing.JScrollPane();
        fParamsTable = new javax.swing.JTable(fParamsTableModel);
        fOptimiseButton = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        setAutoscrolls(true);
        jScrollPane5.setViewportView(fParamsTable);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(jScrollPane5, gridBagConstraints);

        fOptimiseButton.setText("Optimise Portfolio");

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 15, 0);
        add(fOptimiseButton, gridBagConstraints);

    }// </editor-fold>//GEN-END:initComponents

    public void setData(String[] names, double[] meanRets)
    {
        fParamsTableModel.setStockNames(names);
        fParamsTableModel.setDefaultReturns(meanRets);
    }
   
    public void clearData()
    {
        fParamsTableModel.clearData();
    }
    
    public double[] getExpectedReturns()
    {
        return fParamsTableModel.getExpRets();
    }
    
    public double[] getMinAssetWeights()
    {
        return fParamsTableModel.getMinWts();
    }
    
    public double[] getMaxAssetWeights()
    {
        return fParamsTableModel.getMaxWts();
    }
    
    public void setOptimiseButtonListener(ActionListener listen)
    {
        fOptimiseButton.addActionListener(listen);
    }
    
    public void setFontSize(int size)
    {
        Font font = new Font("Dialog", Font.PLAIN, size);
        FontMetrics fm = getFontMetrics(font);

        fOptimiseButton.setFont(font);

        fParamsTable.setFont(font);
        fParamsTable.setRowHeight(fm.getHeight());
        fParamsTable.getTableHeader().setFont(font);

    }
    
    public void updateForLocale(ResourceBundle localSettings)
    {
        fOptimiseButton.setText(localSettings.getString("OptimiseButtonName"));
    }

    public boolean validateParameters()
    {
        boolean retval = false;
        retval = fParamsTableModel.checkWeights();
        return retval;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton fOptimiseButton;
    private javax.swing.JTable fParamsTable;
    // End of variables declaration//GEN-END:variables
    
    private ParamsTableModel fParamsTableModel;
}
