/*
 * PortOptResultsPanel.java
 *
 * Created on 09 August 2006, 14:11
 */

package com.mathworks.demos.finance.portoptdemo;
import java.awt.Font;
import java.awt.FontMetrics;
import java.util.ResourceBundle;

/**
 *
 * @author  elwinc
 */
public class PortOptResultsPanel extends javax.swing.JPanel  implements CustomJComponent {
    
    /**
     * Creates new form PortOptResultsPanel
     */
    public PortOptResultsPanel() {
        fOutputsTableModel = new OutputsTableModel();
        fWeightsTableModel = new WeightsTableModel();
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        fWeightsTable = new javax.swing.JTable(fWeightsTableModel);
        jScrollPane2 = new javax.swing.JScrollPane();
        fRiskReturnTable = new javax.swing.JTable(fOutputsTableModel);

        setLayout(new java.awt.GridBagLayout());

        jSplitPane1.setDividerLocation(150);
        fWeightsTable.setModel(fWeightsTable.getModel());
        jScrollPane1.setViewportView(fWeightsTable);

        jSplitPane1.setRightComponent(jScrollPane1);

        fRiskReturnTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fRiskReturnTableMouseClicked(evt);
            }
        });

        jScrollPane2.setViewportView(fRiskReturnTable);

        jSplitPane1.setLeftComponent(jScrollPane2);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(jSplitPane1, gridBagConstraints);

    }// </editor-fold>//GEN-END:initComponents

    private void fRiskReturnTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fRiskReturnTableMouseClicked

        fWeightsTableModel.selectData(fRiskReturnTable.getSelectedRow());
        
    }//GEN-LAST:event_fRiskReturnTableMouseClicked
    
    public void setData(double[] risk, double[] ret, String[] stockNames, double[][] weights)
    {
        fOutputsTableModel.setData(risk, ret);
        fWeightsTableModel.setData(stockNames, weights);
        
        //select the first risk/return pair
        fWeightsTableModel.selectData(0);
    }
    
    public void clearData()
    {
        fOutputsTableModel.clearData();
        fWeightsTableModel.clearData();
    }
    
    public void setFontSize(int size)
    {
        Font font = new Font("Dialog", Font.PLAIN, size);
        FontMetrics fm = getFontMetrics(font);

        fRiskReturnTable.setFont(font);
        fRiskReturnTable.setRowHeight(fm.getHeight());
        fRiskReturnTable.getTableHeader().setFont(font);

        fWeightsTable.setFont(font);
        fWeightsTable.setRowHeight(fm.getHeight());
        fWeightsTable.getTableHeader().setFont(font);
    }
    
    public void updateForLocale(ResourceBundle localSettings)
    {
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable fRiskReturnTable;
    private javax.swing.JTable fWeightsTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
    
    private OutputsTableModel fOutputsTableModel;
    private WeightsTableModel fWeightsTableModel;

}
