function [] = tdplot(res);
% PURPOSE: Graphic output of temporal disaggregation methods
% ------------------------------------------------------------
% SYNTAX: tdlot(res) 
% ------------------------------------------------------------
% OUTPUT: Graphic output
% ------------------------------------------------------------
% INPUT: res: structure generated by td programs
% ------------------------------------------------------------
% LIBRARY: tduni_plot, td_plot, mtd_plot
% ------------------------------------------------------------
% SEE ALSO: 

% written by:
% Enrique M. Quilis
%  D.G. del Tesoro
%  Paseo del Prado, 6. Office 4.1-3.
%  28014 - Madrid (SPAIN)
%  <equilis@tesoro.meh.es>

% Version 1.1 [August 2006]

if (nargin == 1)
   switch res.meth
   case {'Boot-Feibes-Lisman','Denton','Stram-Wei'}
      tduni_plot(res);
   case {'Fernandez','Chow-Lin','Litterman','Santos Silva-Cardoso'}
      td_plot(res);
   case {'Multivariate Denton','Multivariate Di Fonzo','Multivariate Rossi'}
      mtd_plot(res);
   end
else
   switch res.meth
   case {'Boot-Feibes-Lisman','Denton','Stram-Wei'}
      tduni_plot(res,file_sal);
   case {'Fernandez','Chow-Lin','Litterman','Santos Silva-Cardoso'}
      td_plot(res,file_sal);
   case {'Multivariate Denton','Multivariate Di Fonzo','Multivariate Rossi'}
      mtd_plot(res,file_sal);
   end
end

