function [obj,bound,comp,weight]=estim(obj,in,out,varargin)
%BRRMM.ESTIM    Estimate model parameters from data
%   
%   BRRMM.ESTIM estimates the posterior distribution over model parameters
%   and hidden variables, given a set of data.
%   
%   Usage: [OBJ,BOUND,COMP,WEIGHT] = BRRMM.ESTIM(IN,OUT)
%   
%   Inputs:  IN     - Input data
%            OUT    - Output data containing outliers
%   
%   Outputs: OBJ    - Posterior parameter distributions
%            BOUND  - Variational lower bound
%            COMP   - Posterior component distributions
%            WEIGHT - Posterior output weight distributions
%   
%   IN and OUT contain the input-output data to be processed. IN must be a
%   matrix with NIN rows, where NIN is the number of inputs, and OUT must
%   be a matrix with NOUT rows, where NOUT is the number of outputs. IN and
%   OUT must have the same number of columns. The number of columns is
%   arbitrary. 
%   
%   OBJ is a BRRMM object with the approximate posterior distributions over
%   model parameters. Its size (number of inputs, outputs and components)
%   is the same as in the original object. BOUND contains the variational
%   lower bound on the marginal log-likelihood of the data. BOUND(i) is the
%   bound at the ith iteration.
%   
%   The posterior distributions are estimated by an approximate variational
%   inference algorithm. This algorithm iteratively maximizes a lower bound
%   on the marginal log-likelihood of the data by assuming a structured,
%   factorized approximation to the joint posterior over model parameters
%   and hidden variables.
%   
%   COMP contains the marginal posterior distributions over the components.
%   COMP.PROB(k,j) is the probability that OUT(:,j) was generated by the
%   kth mixture component. WEIGHT contains the conditional posterior
%   distributions over the output weights. If COMP(j)=k, then WEIGHT(j) is
%   Gamma-distributed with mean WEIGHT.MEAN(k,j) and rate WEIGHT.RATE(k,j).
%   
%   The following table summarizes the input/output convention for this
%   function. NIN, NOUT, NCOMP, NPOINT and NITER are, in that order, the
%   number of inputs and outputs, the number of mixture components, the
%   number of points in the input-output data, and the number of iterations
%   upon convergence.
%   
%       Argument          Class      Shape
%       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
%       IN                numeric    NIN-by-NPOINT
%       OUT               numeric    NOUT-by-NPOINT
%       OBJ               BRRMM      1-by-1
%       BOUND             numeric    NITER-by-1
%       COMP.PROB         numeric    NCOMP-by-NPOINT
%       WEIGHT.MEAN       numeric    NSYMB-by-NPOINT
%       WEIGHT.RATE       numeric    NSYMB-by-NPOINT
%       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
%   
%   In addition to the inputs, the syntax 
%   
%   [...] = BRRMM.ESTIM(...,'Prop',Val,...)
%   
%   accepts a list of options in the form of property/value pairs.
%   
%   Options: 'NDEG'  - Number of degrees of freedom
%            'NITER' - Minimum and maximum number of iterations
%            'INIT'  - Parameter initialization method
%            'TEMP'  - Noise temperature for breaking ties
%            'TOL'   - Relative termination tolerance
%   
%   Details: NDEG controls the thickness of the tails of the heavy-tailed
%            component distributions. If NDEG=inf(), then the components
%            are Gaussian; if NDEG is finite, then the components are t
%            distributions.
%   
%            NITER specifies the minimum and maximum number of iterations
%            of the approximate variational inference algorithm. A minimum
%            number is often necessary to avoid premature convergence.
%   
%            INIT specifices the method for initializing the posterior
%            distribution over model parameters. If INIT='none', then the
%            algorithm starts from the last known posterior.
%   
%            TEMP controls the amount of noise applied to the component
%            probabilities in the first iteration. Depending on the type of
%            initialization, this may be necessary in order to break ties.
%   
%            TOL is the relative tolerance for assessing convergence. When
%            the variational lower bound changes by an amount less than or
%            equal to TOL, relative to the previous iteration, the
%            algorithm terminates.
%   
%   See also BRRMM.
%   
%   Copyright (c) 2014 Gabriel Agamennoni.

% Check number of arguments.
if nargin()<3
    error('BRRMM:NotEnoughInputs', ...
        'Not enough inputs.')
end
if nargout()>5
    error('BRRMM:TooManyOutputs', ...
        'Too many outputs.')
end

% Check inputs and scan options from property-value pairs.
[ndeg,niter,init,temp,tol,reg,thres,adapt]=check(obj,in,out,varargin{:});

% Allocate space for variational lower bound.
bound=zeros(max(niter),1);

% Initialize posterior distributions over parameters.
switch lower(init)
    case 'prior'
        obj.post=initparam(obj.prior,in,out);
end

% Initialize flags.
fail=false();
conv=false();

% Run approximate estimation.
for i=1:max(niter)
    
    % Estimate posterior distributions over variables.
    [comp,weight,const]=estimvar(obj.fun,obj.eff,obj.post,in,out,ndeg);
    
    % Randomize on first iteration to break ties.
    if i==1
        [comp,weight]=randvar(comp,weight,temp);
    end
    
    % Evaluate variational lower bound on marginal log-likelihood of data.
    bound(i)=sum(const)-evaldiv(obj.prior,obj.post);
    if reg>0
        bound(i)=bound(i)+evallik(obj.eff,reg);
    end
    
    % Estimate posterior distributions over parameters.
    obj.post=estimparam(obj.fun,obj.eff,obj.prior,comp,weight,in,out);
    
    % Update non-linear effects.
    if isconv(bound(1:i),max(tol))
        if isempty(obj.fun)||isempty(obj.eff)
            conv=true;
        else
            
            % Compute search direction and step size.
            [dir,step,fail,conv]=compdir(obj.fun,obj.eff,obj.post,...
                comp,weight,in,out,reg,thres,adapt,min(tol));
            
            % Update effects.
            obj.eff=obj.eff+step*dir;
            
        end
    end
    
    % Display warning in case of failure.
    if fail
        error('BRRMM:LineSearchFailed',...
            'Line search failed at iteration %d.',i)
    end
    
    % Check convergence.
    if i>=min(niter)&&conv
        bound=bound(1:i);
        break
    end
    
end

end



function [ndeg,niter,init,temp,tol,reg,thres,adapt]=check(obj,in,out,varargin)

% Check object.
if isempty(obj)
    error('BRRMM:BadModelSize', ...
        'Object must be non-empty.')
end
if ndims(obj)>2||numel(obj)>1
    error('BRRMM:BadModelSize', ...
        'Object must be a scalar.')
end

% Store model size.
nin=obj.nin;
nout=obj.nout;

% Initialize argument counter.
arg=0;

% Check inputs.
arg=arg+1;
if ~isnumeric(in)
    error('BRRMM:BadInputClass',...
        'Input %d must be numeric.',arg)
end
if ~isreal(in)
    error('BRRMM:BadInputClass',...
        'Input %d must be real.',arg)
end
if isempty(in)
    error('BRRMM:BadInputSize',...
        'Input %d must be non-empty.',arg)
end
if ndims(in)>2
    error('BRRMM:BadInputSize',...
        'Input %d must be a matrix.',arg)
end
if size(in,1)~=nin
    error('BRRMM:BadInputSize',...
        'Input %d must have %d rows.',arg,nin)
end
if any(isinf(in(:))|isnan(in(:)))
    error('BRRMM:BadInputValue',...
        'Input %d must contain finite numbers.',arg)
end

% Store number of points.
[~,npoint]=size(in);

% Check outputs.
arg=arg+1;
if ~isnumeric(out)
    error('BRRMM:BadInputClass',...
        'Input %d must be numeric.',arg)
end
if ~isreal(out)
    error('BRRMM:BadInputClass',...
        'Input %d must be real.',arg)
end
if isempty(out)
    error('BRRMM:BadInputSize',...
        'Input %d must be non-empty.',arg)
end
if ndims(out)>2
    error('BRRMM:BadInputSize',...
        'Input %d must be a matrix.',arg)
end
if size(out,1)~=nout
    error('BRRMM:BadInputSize',...
        'Input %d must have %d rows.',arg,nout)
end
if size(out,2)~=npoint
    error('BRRMM:BadInputSize',...
        'Input %d must have %d columns.',arg,npoint)
end
if any(isinf(out(:))|isnan(out(:)))
    error('BRRMM:BadInputValue',...
        'Input %d must contain finite numbers.',arg)
end

% Store default options.
ndeg=inf();
niter=[1e1,1e3];
init='prior';
temp=1e-2;
tol=[1e-2,1e-3];
reg=1e-1;
thres=1e-4;
adapt=1/2;

% Scan options from property-value pairs.
for i=1:2:numel(varargin)
    
    % Check for early return.
    if numel(varargin)<i+1
        warning('BRRMM:IgnoringLastInput', ...
            'Ignoring last input.')
        break
    end
    
    % Check property.
    arg=arg+1;
    if ~ischar(varargin{i})
        error('BRRMM:BadInputClass', ...
            'Input %d must be a string.',arg)
    end
    if isempty(varargin{i})
        error('BRRMM:BadInputSize', ...
            'Input %d must be non-empty.',arg)
    end
    if ndims(varargin{i})>2||size(varargin{i},1)>1
        error('BRRMM:BadInputSize', ...
            'Input %d must be a string.',arg)
    end
    
    % Match property to option.
    switch lower(varargin{i})
        case 'ndeg'
            
            % Check number of degrees of freedom.
            arg=arg+1;
            if ~isnumeric(varargin{i+1})
                error('BRRMM:BadInputClass', ...
                    'Input %d must be numeric.',arg)
            end
            if ~isreal(varargin{i+1})
                error('BRRMM:BadInputClass', ...
                    'Input %d must be real.',arg)
            end
            if isempty(varargin{i+1})
                error('BRRMM:BadInputSize', ...
                    'Input %d must be non-empty.',arg)
            end
            if ndims(varargin{i+1})>2||numel(varargin{i+1})>1
                error('BRRMM:BadInputSize', ...
                    'Input %d must be a scalar.',arg)
            end
            if isnan(varargin{i+1})||varargin{i+1}<=0
                error('BRRMM:BadInputValue', ...
                    'Input %d must contain a positive number.',arg)
            end
            
            % Set number of degrees of freedom.
            ndeg=varargin{i+1};
            
        case 'niter'
            
            % Check number of iterations.
            arg=arg+1;
            if ~isnumeric(varargin{i+1})
                error('BRRMM:BadInputClass', ...
                    'Input %d must be numeric.',arg)
            end
            if ~isreal(varargin{i+1})
                error('BRRMM:BadInputClass', ...
                    'Input %d must be real.',arg)
            end
            if isempty(varargin{i+1})
                error('BRRMM:BadInputSize', ...
                    'Input %d must be non-empty.',arg)
            end
            if ndims(varargin{i+1})>2||min(size(varargin{i+1}))>1
                error('BRRMM:BadInputSize', ...
                    'Input %d must be a vector.',arg)
            end
            if any(isnan(varargin{i+1})|isinf(varargin{i+1}))
                error('BRRMM:BadInputValue', ...
                    'Input %d must contain finite numbers.',arg)
            end
            if any(round(varargin{i+1})~=varargin{i+1}|varargin{i+1}<=0)
                error('BRRMM:BadInputValue', ...
                    'Input %d must contain positive integers.',arg)
            end
            
            % Set number of iterations.
            niter=varargin{i+1};
            
        case 'init'
            
            % Check initialization method.
            if ~ischar(varargin{i+1})
                error('BRRMM:BadInputClass',...
                    'Input must be a string.')
            end
            if isempty(varargin{i+1})
                error('BRRMM:BadInputSize',...
                    'Input must be non-empty.')
            end
            if ndims(varargin{i+1})>2||size(varargin{i+1},1)>1
                error('BRRMM:BadInputSize',...
                    'Input must be a string.')
            end
            if ~any(strcmpi(varargin{i+1},{'prior','none'}))
                error('BRRMM:BadInputValue',...
                    'Input must contain a valid method.')
            end
            
            % Set initialization method.
            init=varargin{i+1};
            
        case 'temp'
            
            % Check temperature of initialization noise.
            arg=arg+1;
            if ~isnumeric(varargin{i+1})
                error('BRRMM:BadInputClass', ...
                    'Input %d must be numeric.',arg)
            end
            if ~isreal(varargin{i+1})
                error('BRRMM:BadInputClass', ...
                    'Input %d must be real.',arg)
            end
            if isempty(varargin{i+1})
                error('BRRMM:BadInputSize', ...
                    'Input %d must be non-empty.',arg)
            end
            if ndims(varargin{i+1})>2~=numel(varargin{i+1})>1
                error('BRRMM:BadInputSize', ...
                    'Input %d must be a scalar.',arg)
            end
            if isnan(varargin{i+1})||isinf(varargin{i+1})
                error('BRRMM:BadInputValue', ...
                    'Input %d must contain a finite number.',arg)
            end
            if varargin{i+1}<0||varargin{i+1}>1
                error('BRRMM:BadInputValue', ...
                    'Input %d must contain a number between %d and %d.',arg,0,1)
            end
            
            % Set temperature of initialization noise.
            temp=varargin{i+1};
            
        case 'tol'
            
            % Check relative tolerances.
            arg=arg+1;
            if ~isnumeric(varargin{i+1})
                error('BRRMM:BadInputClass', ...
                    'Input %d must be numeric.',arg)
            end
            if ~isreal(varargin{i+1})
                error('BRRMM:BadInputClass', ...
                    'Input %d must be real.',arg)
            end
            if isempty(varargin{i+1})
                error('BRRMM:BadInputSize', ...
                    'Input %d must be non-empty.',arg)
            end
            if ndims(varargin{i+1})>2||min(size(varargin{i+1}))>1
                error('BRRMM:BadInputSize', ...
                    'Input %d must be a vector.',arg)
            end
            if any(isnan(varargin{i+1})|isinf(varargin{i+1})|varargin{i+1}<=0)
                error('BRRMM:BadInputValue', ...
                    'Input %d must contain positive finite numbers.',arg)
            end
            
            % Set relative tolerances.
            tol=varargin{i+1};
            
        case 'reg'
            
            % Check regularization factor.
            arg=arg+1;
            if ~isnumeric(varargin{i+1})
                error('BRRMM:BadInputClass', ...
                    'Input %d must be numeric.',arg)
            end
            if ~isreal(varargin{i+1})
                error('BRRMM:BadInputClass', ...
                    'Input %d must be real.',arg)
            end
            if isempty(varargin{i+1})
                error('BRRMM:BadInputSize', ...
                    'Input %d must be non-empty.',arg)
            end
            if ndims(varargin{i+1})>2||numel(varargin{i+1})>1
                error('BRRMM:BadInputSize', ...
                    'Input %d must be a scalar.',arg)
            end
            if isnan(varargin{i+1})||isinf(varargin{i+1})||varargin{i+1}<0
                error('BRRMM:BadInputValue', ...
                    'Input %d must contain a non-negative finite number.',arg)
            end
            
            % Set regularization factor.
            reg=varargin{i+1};
            
        case 'thres'
            
            % Check sufficient decrease threshold.
            arg=arg+1;
            if ~isnumeric(varargin{i+1})
                error('BRRMM:BadInputClass', ...
                    'Input %d must be numeric.',arg)
            end
            if ~isreal(varargin{i+1})
                error('BRRMM:BadInputClass', ...
                    'Input %d must be real.',arg)
            end
            if isempty(varargin{i+1})
                error('BRRMM:BadInputSize', ...
                    'Input %d must be non-empty.',arg)
            end
            if ndims(varargin{i+1})>2||numel(varargin{i+1})>1
                error('BRRMM:BadInputSize', ...
                    'Input %d must be a scalar.',arg)
            end
            if isnan(varargin{i+1})||isinf(varargin{i+1})||varargin{i+1}<=0
                error('BRRMM:BadInputValue', ...
                    'Input %d must contain a positive finite number.',arg)
            end
            
            % Set sufficient decrease threshold.
            thres=varargin{i+1};
            
        case 'adapt'
            
            % Check step size adaptation factor.
            arg=arg+1;
            if ~isnumeric(varargin{i+1})
                error('BRRMM:BadInputClass', ...
                    'Input %d must be numeric.',arg)
            end
            if ~isreal(varargin{i+1})
                error('BRRMM:BadInputClass', ...
                    'Input %d must be real.',arg)
            end
            if isempty(varargin{i+1})
                error('BRRMM:BadInputSize', ...
                    'Input %d must be non-empty.',arg)
            end
            if ndims(varargin{i+1})>2||numel(varargin{i+1})>1
                error('BRRMM:BadInputSize', ...
                    'Input %d must be a scalar.',arg)
            end
            if isnan(varargin{i+1})||isinf(varargin{i+1})
                error('BRRMM:BadInputValue', ...
                    'Input %d must contain a finite number.',arg)
            end
            if varargin{i+1}<=0||varargin{i+1}>=1
                error('BRRMM:BadInputValue',...
                    'Input %d must contain a value between %d and %d.',arg,0,1)
            end
            
            % Set step size adaptation factor.
            adapt=varargin{i+1};
            
        otherwise
            error('BRRMM:BadProperty', ...
                'Input %d is not a valid option.',arg)
    end
    
end

end