function createmenubar(hfig)
% Function to create the tatool menubar.
% Note that all uimenu items have a tag.  This tag will be used later in
% conjunction with guidata to get the object handles.
%
% Example:
% None needed - this is a UI helper function that should not be called
% directly
%

try
    % Error if hfig isn't a figure handle
    figtype = get(hfig,'Type');
    if ~strcmp('figure',figtype)
        error('');
    end
catch
    str = 'Input must be a handle to a figure window.';
    error(str);
    return
end

% Create the menubar

% Define the main menus across the UI
hstruct.file = uimenu('Parent',hfig,'Label','&File','Tag','uimenufile');
hstruct.edit = uimenu('Parent',hfig,'Label','&Edit','Tag','uimenuedit');
hstruct.timerange = uimenu('Parent',hfig,'Label','&Time Range','Tag','uimenutimerange');
hstruct.indicators = uimenu('Parent',hfig,'Label','&Indicators','Tag','uimenuindicators');
hstruct.help = uimenu('Parent',hfig,'Label','&Help','Tag','uimenuhelp');

%%%%%%%%%%%%%%%%%% Define the 'File' pulldown menus %%%%%%%%%%%%%%%%%%
h = uimenu('Parent',hstruct.file,...
    'Label','Import',...
    'Tag','uimenufileimport');
uimenu('Parent',h,...
    'Label','Ticker from Yahoo.com',...
    'Callback',@uimenufileimportcb,...
    'Tag','uimenufileimportyahoo');
uimenu('Parent',h,...
    'Label','Numeric Array',...
    'Callback',@uimenufileimportcb,...
    'Tag','uimenufileimportarray');
uimenu('Parent',h,...
    'Label','Structure with Dates and Data',...
    'Callback',@uimenufileimportcb,...
    'Tag','uimenufileimportstruct');
% The import of time series objects is dependent on version and product
% licensing
v = ver('MATLAB');
if (str2double(v.Version)>=(7.2-eps))
    % This is version 7.2 or above, so have an option to load a MATLAB time series
    % object
    uimenu('Parent',h,...
    'Label','MATLAB Time Series Object',...
    'Callback',@uimenufileimportcb,...
    'Tag','uimenufileimportMATLABts');
    if license('test','FINANCIAL_TOOLBOX') % user is licensed for Financial Toolbox
        uimenu('Parent',h,...
            'Label','Financial Toolbox Time Series Object',...
            'Callback',@uimenufileimportcb,...
            'Enable','on',...
            'Tag','uimenufileimportfints');
    end
else % This is an older version so test for financial time series toolbox
    if license('test','Fin_Time_Series_Toolbox') % user is licensed for Financial Toolbox
        uimenu('Parent',h,...
            'Label','Financial Time Series Object',...
            'Callback',@uimenufileimportcb,...
            'Enable','on',...
            'Tag','uimenufileimportfints');
    end
end

h = uimenu('Parent',hstruct.file,...
    'Label','Export',...
    'Enable','off',...
    'Tag','uimenufileexport');
uimenu('Parent',h,...
    'Label','Structure with Dates and Data',...
    'Callback',@uimenufileexportcb,...
    'Tag','uimenufileexportstruct');

if (str2double(v.Version)>=(7.2-eps))
    % This is version 7.2 or above
    uimenu('Parent',h,...
        'Label','MATLAB Time Series Object',...
        'Callback',@uimenufileexportcb,...
        'Tag','uimenufileexportMATLABts');
    if license('test','FINANCIAL_TOOLBOX') % user is licensed for Finacial Toolbox
        uimenu('Parent',h,...
            'Label','Financial Toolbox Time Series Object',...
            'Callback',@uimenufileexportcb,...
            'Enable','on',...
            'Tag','uimenufileexportfints');
    end
else %This is a version earlier than R2006a
    if license('test','Fin_Time_Series_Toolbox') % user is licensed for FTS Toolbox
        uimenu('Parent',h,...
            'Label','Financial Time Series Object',...
            'Callback',@uimenufileexportcb,...
            'Enable','on',...
            'Tag','uimenufileexportfints');
    end
end

uimenu('Parent',hstruct.file,...
    'Label','Pa&ge Setup...',...
    'Separator','on',...
    'Enable','off',...
    'Callback','pagesetupdlg(gcbf);',...
    'Tag','uimenufilepagesetup');
uimenu('Parent',hstruct.file,...
    'Label','Print Set&up...',...
    'Enable','off',...
    'Callback','printdlg(''-setup'');',...
    'Tag','uimenufileprintsetup');
uimenu('Parent',hstruct.file,...
    'Label','Print Pre&view...',...
    'Enable','off',...
    'Callback','printpreview(gcbf);',...
    'Tag','uimenufileprintpreview');
uimenu('Parent',hstruct.file,...
    'Label','&Print...',...
    'Enable','off',...
    'Callback','printdlg(gcbf);',...
    'Tag','uimenufileprint');

uimenu('Parent',hstruct.file,...
    'Label','&Close',...
    'Separator','on',...
    'Callback',@uimenufilecb,...
    'Tag','uimenufileclose');



%%%%%%%%%%%%%%%%%% Define the 'Edit' pulldown menus %%%%%%%%%%%%%%%%%%
uimenu('Parent',hstruct.edit,...
    'Label','Reorder Axes',...
    'Callback',@uimenueditcb,...
    'Enable','off',...
    'Tag','uimenueditreorder');
uimenu('Parent',hstruct.edit,...
    'Label','&Zoom On',...
    'Separator','on',...
    'Callback',@uimenueditcb,...
    'Enable','off',...
    'Tag','uimenueditzoomon');
uimenu('Parent',hstruct.edit,...
    'Label','Zoom &Off',...
    'Callback',@uimenueditcb,...
    'Enable','off',...
    'Tag','uimenueditzoomoff');

%%%%%%%%%%%%%%%%%% Define the 'Time Range' pulldown menus %%%%%%%%%%%%%%%%%%
uimenu('Parent',hstruct.timerange,...
    'Label','All',...
    'Callback',@uimenutimerangecb,...
    'Enable','off',...
    'Tag','uimenutimerangeall');
uimenu('Parent',hstruct.timerange,...
    'Label','Year to Date',...
    'Callback',@uimenutimerangecb,...
    'Enable','off',...
    'Tag','uimenutimerangeytd');
uimenu('Parent',hstruct.timerange,...
    'Label','Last 5 Trading Days',...
    'Separator','on',...
    'Callback',@uimenutimerangecb,...
    'Enable','off',...
    'Tag','uimenutimerange5days');
uimenu('Parent',hstruct.timerange,...
    'Label','Last 30 Trading Days',...
    'Callback',@uimenutimerangecb,...
    'Enable','off',...
    'Tag','uimenutimerange30days');
uimenu('Parent',hstruct.timerange,...
    'Label','Last 3 Months',...
    'Separator','on',...
    'Callback',@uimenutimerangecb,...
    'Enable','off',...
    'Tag','uimenutimerange3months');
uimenu('Parent',hstruct.timerange,...
    'Label','Last 6 Months',...
    'Callback',@uimenutimerangecb,...
    'Enable','off',...
    'Tag','uimenutimerange6months');
uimenu('Parent',hstruct.timerange,...
    'Label','Last 12 Months',...
    'Callback',@uimenutimerangecb,...
    'Enable','off',...
    'Tag','uimenutimerange12months');
uimenu('Parent',hstruct.timerange,...
    'Label','Last 2 Years',...
    'Separator','on',...
    'Callback',@uimenutimerangecb,...
    'Enable','off',...
    'Tag','uimenutimerange2years');
uimenu('Parent',hstruct.timerange,...
    'Label','Last 3 Years',...
    'Callback',@uimenutimerangecb,...
    'Enable','off',...
    'Tag','uimenutimerange3years');
uimenu('Parent',hstruct.timerange,...
    'Label','Last 5 Years',...
    'Callback',@uimenutimerangecb,...
    'Enable','off',...
    'Tag','uimenutimerange5years');
uimenu('Parent',hstruct.timerange,...
    'Label','Last 10 Years',...
    'Callback',@uimenutimerangecb,...
    'Enable','off',...
    'Tag','uimenutimerange10years');

%%%%%%%%%%%%%%%%%% Define the 'Indicators' pulldown menus %%%%%%%%%%%%%%%%%%
h = uimenu('Parent',hstruct.indicators,...
    'Label','Bollinger Bands',...
    'Enable','off',...
    'Tag','uimenuindicatorsbollingerul');
uimenu('Parent',h,...
    'Label','New',...
    'Callback',{@uimenuindicatorscb,'mainaxes','bollingerul',...
        {'Period:',10,'Number STD''s:',2}},...
    'Tag','uimenuindicatorsbollingerulnew');

h = uimenu('Parent',hstruct.indicators,...
    'Label','Commodity Channel Index',...
    'Enable','off',...
    'Tag','uimenuindicatorscci');
uimenu('Parent',h,...
    'Label','New',...
    'Callback',{@uimenuindicatorscb,'ownaxes','cci',{'Period:',20}},...
    'Tag','uimenuindicatorsccinew');

h = uimenu('Parent',hstruct.indicators,...
    'Label','Detrended Price Oscillator',...
    'Enable','off',...
    'Tag','uimenuindicatorsdpo');
uimenu('Parent',h,...
    'Label','New',...
    'Callback',{@uimenuindicatorscb,'ownaxes','dpo',{'Period:',10}},...
    'Tag','uimenuindicatorsdponew');

h = uimenu('Parent',hstruct.indicators,...
    'Label','Envelopes (Trading Bands)',...
    'Enable','off',...
    'Tag','uimenuindicatorsetb');
uimenu('Parent',h,...
    'Label','New',...
    'Callback',{@uimenuindicatorscb,'mainaxes','etb',{'Period:',20,'Percent move:',1}},...
    'Tag','uimenuindicatorsetbnew');

h = uimenu('Parent',hstruct.indicators,...
    'Label','Linear Regression Indicator',...
    'Enable','off',...
    'Tag','uimenuindicatorslr');
uimenu('Parent',h,...
    'Label','New',...
    'Callback',{@uimenuindicatorscb,'mainaxes','lri',{'Period:',14}},...
    'Tag','uimenuindicatorslrinew');

h = uimenu('Parent',hstruct.indicators,...
    'Label','MACD',...
    'Enable','off',...
    'Tag','uimenuindicatorsmacd');
uimenu('Parent',h,...
    'Label','New',...
    'Callback',{@uimenuindicatorscb,'ownaxes','macd',...
    {'Period:',26,'Period:',12,'Period:',9}},...
    'Tag','uimenuindicatorsmacdnew');

h = uimenu('Parent',hstruct.indicators,...
    'Label','Momentum',...
    'Enable','off',...
    'Tag','uimenuindicatorsmomentum');
uimenu('Parent',h,...
    'Label','New',...
    'Callback',{@uimenuindicatorscb,'ownaxes','momentum',{'Period:',10}},...
    'Tag','uimenuindicatorsmomentumnew');

hma = uimenu('Parent',hstruct.indicators,...
    'Label','Moving Averages',...
    'Enable','off',...
    'Tag','uimenuindicatorsma');

h = uimenu('Parent',hma,...
    'Label','Double Exponential',...
    'Enable','on',...
    'Tag','uimenuindicatorsdema');
uimenu('Parent',h,...
    'Label','New',...
    'Callback',{@uimenuindicatorscb,'mainaxes','dema',{'Period:',10}},...
    'Tag','uimenuindicatorsdemanew');

h = uimenu('Parent',hma,...
    'Label','Exponential',...
    'Enable','on',...
    'Tag','uimenuindicatorsema');
uimenu('Parent',h,...
    'Label','New',...
    'Callback',{@uimenuindicatorscb,'mainaxes','ema',{'Period:',10}},...
    'Tag','uimenuindicatorsemanew');

h = uimenu('Parent',hma,...
    'Label','Simple',...
    'Enable','on',...
    'Tag','uimenuindicatorssma');
uimenu('Parent',h,...
    'Label','New',...
    'Callback',{@uimenuindicatorscb,'mainaxes','sma',{'Period:',10}},...
    'Tag','uimenuindicatorssmanew');

h = uimenu('Parent',hma,...
    'Label','Weighted',...
    'Enable','on',...
    'Tag','uimenuindicatorswma');
uimenu('Parent',h,...
    'Label','New',...
    'Callback',{@uimenuindicatorscb,'mainaxes','wma',{'Period:',10}},...
    'Tag','uimenuindicatorswmanew');

h = uimenu('Parent',hstruct.indicators,...
    'Label','ROC',...
    'Enable','off',...
    'Tag','uimenuindicatorsroc');
uimenu('Parent',h,...
    'Label','New',...
    'Callback',{@uimenuindicatorscb,'ownaxes','roc',{'Period:',14}},...
    'Tag','uimenuindicatorsrocnew');

h = uimenu('Parent',hstruct.indicators,...
    'Label','RSI',...
    'Enable','off',...
    'Tag','uimenuindicatorsrsi');
uimenu('Parent',h,...
    'Label','New',...
    'Callback',{@uimenuindicatorscb,'ownaxes','rsi',{'Period:',10}},...
    'Tag','uimenuindicatorsrsinew');

h = uimenu('Parent',hstruct.indicators,...
    'Label','Wilder Smoothing',...
    'Enable','off',...
    'Tag','uimenuindicatorswildersmoothing');
uimenu('Parent',h,...
    'Label','New',...
    'Callback',{@uimenuindicatorscb,'mainaxes','wildersmoothing',{'Period:',10}},...
    'Tag','uimenuindicatorswildersmoothingnew');

%%%%%%%%%%%%%%%%%% Define the 'Help' pulldown menus %%%%%%%%%%%%%%%%%%
uimenu('Parent',hstruct.help,...
    'Label','Help',...
    'Callback',@uimenuhelpcb,...
    'Tag','uimenuhelphelp');
uimenu('Parent',hstruct.help,...
    'Label','About',...
    'Separator','on',...
    'Callback',@uimenuhelpcb,...
    'Tag','uimenuhelpabout');

