%HELPOPT  Help with glmlab options

%Copyright 1996--1998 Peter Dunn
%02 March 1998 

TITSTR_ = 'glmlab Menu Explanations';

PAGE1_ = {'To display options, click on the section.  Current settings are indicated.',...
' ',...
'FILE:      Load data; Load and Save glmlab sessions; Close glmlab windows; Quit glmlab.',...
' ',...
'DISTRIBUTION:      Click for choices of available error distributions.',...
' ',...
'LINK:      Click for choices of available link functions.',...
' ',...
'SCALE PARAMETER:      Either the mean deviance or a fixed value.  To enter a particular value, select ''Fixed Value'' and you will be prompted.',...
' ',...
'RESIDUALS:      Click for choices of available error types.',...
' ',...
' (cont...)'};

PAGE2_ = {'OPTIONS:      Reset the options to their defaults; declare a new model; include a constant term in the fit; alter output display; recycle fitted values as starting values in the next iteration of the fit.',...
' ',...
'HELP:      Get some basic help (didn''t you just do this?).',...
' ',...
'FIT MODEL:      Fits the model as specified.'};

glhelp(TITSTR_, PAGE1_, PAGE2_);
clear TITSTR_ PAGE1_ PAGE2_
