%HELPOV Help about glmlab's output variables

%Copyright 1996--1998 Peter Dunn
%02 March 1998

TITSTR_ = 'Information About  glmlab''s Output Variables';

PAGE1_ = {'BETA:  The parameter estimates',...
' ',...
'SERRORS:  The standard errors of the parameter estimates',...
' ',...
'FITS:  The fitted values',...
' ',...
'RESIDS:  The residuals (determined by the Residual type)',...
' ',...
'COVB:  The covariance matrix of beta',...
' ',...
'COVD:  The covariance matrix of the difference in the betas',...
' ',...
'DEVLIST:  The deviance at each iteration of the fit',...
' ',...
'LINPRED:  The linear predictor (usually written as  eta)',...
' ',...
'XMATRIX:  The covariates matrix used',...
' ',...
'XVARNAMES:  The names of the X-variables used'};

glhelp(TITSTR_, PAGE1_);
clear TITSTR_ PAGE1_
