%HELPCONT  contat information for  glmlab

%Copyright 1996--1998, Peter Dunn
%02 March 1998

TITSTR_ = 'How to Contact the Author';

PAGE1_={'The author of  glmlab  is Peter K Dunn of the University of Southern Queensland, Queensland, Toowoomba, AUSTRALIA.',...
' ',...
'I would be happy to get some feedback from you about  glmlab, whether you have comments, jokes, errors, money :->, or suggestions.  However, I cannot guarantee that I can fix any errors or implement any suggestions.',...
' ',...
'I am no  MATLAB  expert, so the code is probably not optimised, so any suggestions for enhancements in that area would be gratefully accepted.',...
' ',...
'If you''re using  glmlab, drop me an email and tell me what you think, or complain or whinge or whatever. You can find me at:',...
'   dunn@sci.usq.edu.au'};


glhelp(TITSTR_,PAGE1_);
clear TITSTR_ PAGE1_
