%HELPINT  Help with interactions in glmlab

%Copyright 1996--1998 Peter Dunn
%02 march 1998

TITSTR_ = 'INTERACTIONS USING  glmlab';


PAGE1_={'In glmlab, interactions are specified using the  @  character, which is usually  shift-2  on the keyboard.  Interactions between variables are specified by separating them using  @.',...
' ',...
'For example, consider variables named:  Weight, Height, Risk, Gender',...
' ',...
'Type',...
'    Risk',...
'in the Response area of the glmlab Main Screen, and in the Covariates area, type:',...
'    Weight@Height',...
' ',...
'This will specifiy the interaction between Height and Weight.',...
' ',...
'(cont...)'};

PAGE2_= {'When qualitative variables are involved, use the  fac  command as usual.  So, to specify the interaction between  Height  and  Gender, use',...
'    Height@fac(Gender)',...
' ',...
'In practice, the Covariate list will be longer than this; for example:',...
    'Weight, fac(Gender), fac(Gender)@Height, Weight'};

glhelp(TITSTR_, PAGE1_, PAGE2_);
clear TITSTR_ PAGE1_ PAGE2_
