%HELPPLOT Help about  glmlab's  plotting functions

%Copyright 1996--1998 Peter Dunn
%02 March 1998

TITSTR_ = 'THE  glmlab  RESIDUALS PLOTS WINDOW';

PAGE1_ = {'After fitting a model, the  PLOTS  menu apppears.  There are a number of plots which you can let  glmlab  plot for you:',...
' ',...
'Residuals versus the Response (y) variable;',' ',...
'Residuals versus any combination of the Covariates (a new window will appear asking you which of the co-variates you wish to select for your plot(s).  At the moment only up to thirty covariates work.',' ',...
'Normal Probability Plot:  If the residuals are normally distributed, the points will lie around the given line;',' ',...
'Residuals versus Fitted Values;',' ',...
'Residuals versus Transformed Fitted Values:  The transformation makes a constant information scale for the given distribution;',' ',...
'Fitted Values vs Quantile Equivalents.'};

glhelp(TITSTR_, PAGE1_);
clear TITSTR_ PAGE1_
