%HELPVARS  Help with using  glmlab  main window

%Copyright 1996--1998 Peter Dunn
%02 March 1998

TITSTR_ = 'Help with glmlab Variables';

PAGE1_ = {'Variable names used must refer to variables already defined in the workspace. To be safe, don''t use variable whose names are all CAPITAL letters.',' ',...
'Response (y):     Type the name of the response (y) variable.  For the binomial case, use two columns:',...
'                  [counts   sample size]',' ',...
'Covarites (X):     Enter the list of covariates (X values).  The inclusion of the Constant Term is controlled in the OPTIONS menu.  Interactions are specified with the  @  character. ',' ',...
'Prior Weights:     Enter the name of the prior weights variable.',' ',...
'Offset Variable:     Enter the name of the offset variable.',' ',...
'Fit Model:     Fits the model as currently specified.',' ',...
'Residual Plots:     The menu screen for plots about residuals.',' ',...
'New Model:  Resets everything for fitting a new model.'};

glhelp(TITSTR_, PAGE1_);
clear TITSTR_ PAGE1_
