%HELPGET  Help screen for obtaining  glmlab

%Copyright 1996--1998 Peter Dunn
%02 March 1998

figure('Units','normal','Resize','off','HandleVisibility','Callback',...
   'Name','Information for Obtaining  glmlab','NumberTitle','off');
uicontrol('Style','pushbutton','String','Finished','Units','normalized',...
 'Position',[.4 .01 .2 .08],'Callback','delete(gcf);');
uicontrol('Style','pushbutton','String','MathWorks Home Page',...
 'Units','normalized','Position',[.05 .01 .33 .08],...
 'Callback','web(''http://www.mathworks.com'');');
uicontrol('Style','pushbutton','String','glmlab  Home Page',...
 'Units','normalized','Position',[.62 .01 .3 .08],...
 'Callback','web(''www.sci.usq.edu.au/staff/dunn/glmlab/glmlab.html'');');


uicontrol(gcf,'Style','Frame','Units','Normalized',...
       'Position',[.05 .25 .9 .65]);
HT_=uicontrol(gcf,'Style','Text','Units','Normalized','FontSize',12,...
       'Position',[.1 .3 .8 .6]);

INSTRING_={'HOW TO GET THE LATEST VERISON OF  glmlab','',...
   ['glmlab  is available from the MathWorks Web Site in the User-',...
    'Contributed Files area.  It is updated at times, but there are no plans ',...
    'for any major changes (errors permitting :-> ).'],'',...
    'The latest (zip/tar) version can be found at the MathWorks Web site:',...
    'http://www.mathworks.com/statsv5.html','',...
    'You might like to visit the  glmlab ''Home Page'': ',...
    'http://www.sci.usq.edu.au/staff/dunn/glmlab/glmlab.html'};
[OUTSTR_,NEWPOS_]=textwrap(HT_,INSTRING_);
set(HT_,'String',OUTSTR_,'Position',NEWPOS_);
clear OUTSTR_ NEWPOS_ INSTRING_ HT_
