// MatInfo.idl : IDL source for MatInfo.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (MatInfo.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
	[
		object,
		uuid(51BBEC40-17CA-422f-B344-8B2BE6343F17),
		dual,
		helpstring("IMatInfoShlExt Interface"),
		pointer_default(unique)
	]
	interface IMatInfoShlExt : IDispatch
	{
	};

[
	uuid(664BD649-C887-42ca-9FE9-48AE6083F17E),
	version(1.0),
	helpstring("MatInfo 1.0 Type Library")
]
library TXTINFOLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[
		uuid(6161C834-86DE-4cdd-BA3F-8E1E8631EABA),
		helpstring("MatInfoShlExt Class")
	]
	coclass MatInfoShlExt
	{
		[default] interface IMatInfoShlExt;
	};
};
